sudo: required
services:
  - docker

before_install:
  - docker build -t chrisbriant/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chrisbriant/react-test npm test

after_success:
  - docker build -t chrisbriant/multi-client ./client
  - docker build -t chrisbriant/multi-nginx ./nginx
  - docker build -t chrisbriant/multi-server ./server
  - docker build -t chrisbriant/multi-worker ./worker
  #Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push to docker hub
  - docker push chrisbriant/multi-client
  - docker push chrisbriant/multi-nginx
  - docker push chrisbriant/multi-server
  - docker push chrisbriant/multi-worker