sudo: required
services:
  - docker

before_install:
  - docker build -t thundercatsho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thundercatsho/react-test npm test

after_success:
  - docker build -t thundercatsho/multi-client ./client
  - docker build -t thundercatsho/multi-nginx ./nginx
  - docker build -t thundercatsho/multi-server ./server
  - docker build -t thundercatsho/multi-worker ./worker
  #Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push to docker hub
  - docker push thundercatsho/multi-client
  - docker push thundercatsho/multi-nginx
  - docker push thundercatsho/multi-server
  - docker push thundercatsho/multi-worker